# This is a basic workflow to help you get started with Actions

name: Backup Core Solution to Source Control

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Power Platform Tool Installer
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ secrets.ENVIRONMENT_URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-name: ${{ secrets.SOLUTION_NAME }}
          solution-output-file: out/export/${{ secrets.SOLUTION_NAME }}.zip
          managed: false
          
      - name: Unpack-Solution-Action
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: out/export/${{ secrets.SOLUTION_NAME }}.zip
          solution-folder: out/solutions/${{ secrets.SOLUTION_NAME }}
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: branch-solution, prepare it for a PullRequest
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: out/solutions/${{ secrets.SOLUTION_NAME }}
          solution-target-folder: solutions/${{ secrets.SOLUTION_NAME }}
          repo-token: ${{ secrets.PAT_TOKEN }}
          allow-empty-commit: true
